// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using taifi_travel_back.Data;

#nullable disable

namespace taifi_travel_back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260822175237_DateOfBirthToDate")]
    partial class DateOfBirthToDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("taifi_travel_back.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationType")
                        .HasColumnType("text");

                    b.Property<bool>("CertificateDeposited")
                        .HasColumnType("boolean");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedByWorkerId")
                        .HasColumnType("integer");

                    b.Property<bool>("FinalValidation")
                        .HasColumnType("boolean");

                    b.Property<int?>("HotelOfferId")
                        .HasColumnType("integer");

                    b.Property<bool>("PassportDeposited")
                        .HasColumnType("boolean");

                    b.Property<bool>("PhotoDeposited")
                        .HasColumnType("boolean");

                    b.Property<int?>("TripId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedByWorkerId");

                    b.HasIndex("HotelOfferId");

                    b.HasIndex("TripId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("taifi_travel_back.Models.ClientProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("CinNumber")
                        .HasColumnType("text");

                    b.Property<int?>("CreatedByWorkerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CinNumber")
                        .IsUnique();

                    b.HasIndex("CreatedByWorkerId");

                    b.ToTable("ClientProfiles");
                });

            modelBuilder.Entity("taifi_travel_back.Models.HajjDetails", b =>
                {
                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<int?>("CalculatedAge")
                        .HasColumnType("integer");

                    b.Property<string>("TestStatus")
                        .HasColumnType("text");

                    b.Property<string>("WorkerRole")
                        .HasColumnType("text");

                    b.HasKey("ApplicationId");

                    b.ToTable("HajjDetails");
                });

            modelBuilder.Entity("taifi_travel_back.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<List<string>>("ImagesBase64")
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("taifi_travel_back.Models.HotelOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4);

                    b.Property<int>("HotelId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("HotelOffers");
                });

            modelBuilder.Entity("taifi_travel_back.Models.HotelPaymentLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedByWorkerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TripId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedByWorkerId");

                    b.HasIndex("TripId");

                    b.ToTable("HotelPaymentLogs");
                });

            modelBuilder.Entity("taifi_travel_back.Models.OmraDetails", b =>
                {
                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.HasKey("ApplicationId");

                    b.ToTable("OmraDetails");
                });

            modelBuilder.Entity("taifi_travel_back.Models.PaymentLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedByWorkerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TripId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedByWorkerId");

                    b.HasIndex("TripId");

                    b.ToTable("PaymentLogs");
                });

            modelBuilder.Entity("taifi_travel_back.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedByWorkerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DepartureDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("ImagesBase64")
                        .HasColumnType("text[]");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("TripType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByWorkerId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("taifi_travel_back.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("ContactValid")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("taifi_travel_back.Models.WorkerAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PermissionsJson")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Agent");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("WorkerAccounts");
                });

            modelBuilder.Entity("taifi_travel_back.Models.Application", b =>
                {
                    b.HasOne("taifi_travel_back.Models.ClientProfile", "Client")
                        .WithMany("Applications")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("taifi_travel_back.Models.WorkerAccount", "CreatedByWorker")
                        .WithMany()
                        .HasForeignKey("CreatedByWorkerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("taifi_travel_back.Models.HotelOffer", "HotelOffer")
                        .WithMany("Applications")
                        .HasForeignKey("HotelOfferId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("taifi_travel_back.Models.Trip", "Trip")
                        .WithMany("Applications")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Client");

                    b.Navigation("CreatedByWorker");

                    b.Navigation("HotelOffer");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("taifi_travel_back.Models.ClientProfile", b =>
                {
                    b.HasOne("taifi_travel_back.Models.UserAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("taifi_travel_back.Models.WorkerAccount", "CreatedByWorker")
                        .WithMany()
                        .HasForeignKey("CreatedByWorkerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("CreatedByWorker");
                });

            modelBuilder.Entity("taifi_travel_back.Models.HajjDetails", b =>
                {
                    b.HasOne("taifi_travel_back.Models.Application", "Application")
                        .WithOne("HajjDetails")
                        .HasForeignKey("taifi_travel_back.Models.HajjDetails", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("taifi_travel_back.Models.HotelOffer", b =>
                {
                    b.HasOne("taifi_travel_back.Models.Hotel", "Hotel")
                        .WithMany("HotelOffers")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("taifi_travel_back.Models.HotelPaymentLog", b =>
                {
                    b.HasOne("taifi_travel_back.Models.ClientProfile", "Client")
                        .WithMany("HotelPaymentLogs")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("taifi_travel_back.Models.WorkerAccount", "CreatedByWorker")
                        .WithMany()
                        .HasForeignKey("CreatedByWorkerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("taifi_travel_back.Models.Trip", "Trip")
                        .WithMany("HotelPaymentLogs")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Client");

                    b.Navigation("CreatedByWorker");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("taifi_travel_back.Models.OmraDetails", b =>
                {
                    b.HasOne("taifi_travel_back.Models.Application", "Application")
                        .WithOne("OmraDetails")
                        .HasForeignKey("taifi_travel_back.Models.OmraDetails", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("taifi_travel_back.Models.PaymentLog", b =>
                {
                    b.HasOne("taifi_travel_back.Models.ClientProfile", "Client")
                        .WithMany("PaymentLogs")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("taifi_travel_back.Models.WorkerAccount", "CreatedByWorker")
                        .WithMany()
                        .HasForeignKey("CreatedByWorkerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("taifi_travel_back.Models.Trip", "Trip")
                        .WithMany("PaymentLogs")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Client");

                    b.Navigation("CreatedByWorker");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("taifi_travel_back.Models.Trip", b =>
                {
                    b.HasOne("taifi_travel_back.Models.WorkerAccount", "CreatedByWorker")
                        .WithMany()
                        .HasForeignKey("CreatedByWorkerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByWorker");
                });

            modelBuilder.Entity("taifi_travel_back.Models.Application", b =>
                {
                    b.Navigation("HajjDetails");

                    b.Navigation("OmraDetails");
                });

            modelBuilder.Entity("taifi_travel_back.Models.ClientProfile", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("HotelPaymentLogs");

                    b.Navigation("PaymentLogs");
                });

            modelBuilder.Entity("taifi_travel_back.Models.Hotel", b =>
                {
                    b.Navigation("HotelOffers");
                });

            modelBuilder.Entity("taifi_travel_back.Models.HotelOffer", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("taifi_travel_back.Models.Trip", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("HotelPaymentLogs");

                    b.Navigation("PaymentLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
